#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Fri Apr 24 17:34:07 2009

import wx, Image
from decorators import *

# begin wxGlade: extracode
# end wxGlade



class GradientFrame(wx.Frame):
    def __init__(self, parent):
        self.title = "Gradient Tweaker"
        self.parent = parent
        wx.Frame.__init__(self, parent, wx.ID_ANY, self.title)

        self.gradient = GradientPanel(self)
#        self.choice_1 = wx.Choice(self, -1, choices=["Hue", "Saturation", "Brightness", "Blur", "Rotate"])
#        self.slider_1 = wx.Slider(self, -1, 0, 0, 10)
#        self.label_1 = wx.StaticText(self, -1, "256")

        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        # begin wxGlade: wxFrame.__set_properties
        self.SetTitle("Gradient Tweaker")
        self.SetSize((528, 60))
        self.gradient.SetMinSize((512, 50))
#        self.choice_1.SetMinSize((110, 21))
#        self.choice_1.SetSelection(0)
#        self.slider_1.SetMinSize((360, -1))
#        self.label_1.SetMinSize((27, 19))
#        self.label_1.SetBackgroundColour(wx.Colour(255, 255, 255))
#        self.label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))

    def __do_layout(self):
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
#        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.gradient, 0, 0, 0)
#        sizer_2.Add(self.choice_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
#        sizer_2.Add(self.slider_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
#        sizer_2.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 1)
#        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        
    def UpdateGradient(self):
        self.gradient.refresh()
        self.Refresh()
# end of class GradientFrame

class GradientPanel(wx.Panel):

    @BindEvents    
    def __init__(self,parent):
        self.parent = parent
        wx.Panel.__init__(self, parent, wx.ID_ANY)
        self.bmp = wx.EmptyBitmap(512,50,32)

    def refresh(self):
        if self.parent.parent.flame:
            self.bmp = get_bitmap(self.parent.parent.flame.gradient)
        else:
            self.bmp = wx.EmptyBitmap(512,50,32)

    @Bind(wx.EVT_PAINT)
    def OnPaint(self, evt):
        self.refresh()
        fw,fh = self.bmp.GetSize()
        dc = wx.PaintDC(self)
        pw,ph = self.parent.GetSize()
        dc.DrawBitmap(self.bmp, (pw-fw)/2, (ph-fh)/2, True)


def get_bitmap(gradient):
    i = Image.new("RGB", (256, 50))
    i.putdata(gradient*50)
    i = i.resize((512,50))
    image = wx.EmptyImage(512, 50)
    image.SetData(i.convert("RGB").tostring())
    image.SetAlphaData(i.convert("RGBA").tostring()[3::4])
    return wx.BitmapFromImage(image)
